### ISSUE TITLE
addressees in To: field not visible

### ISSUE THREAD

**Issue by bvdlingen** [eNkru/freelook#25] opened 2019-12-21 09:55 UTC
Happy I stumbled upon this great app!

After using it a few days, I only discovered 1 minor issue:

When composing a new email or replying to an email the addresses in the To: field are not visible
They are there however; I am able to send the email

**Comment by eNkru** [comment] 2020-01-06 03:23
@bvdlingen if I remember correct, this issue is reported by another user with deepin Linux.

Could you let me know which distribution are you using and maybe a screenshot of the issue is helping. 

I really couldn't reproduce it. I reckon it's something wrong with the UI CSS

**Comment by bvdlingen** [comment] 2020-01-09 15:10
Thanks for the follow up,

I am running [Solus](https://getsol.us/home/) Linux, with [Budgie desktop](https://github.com/solus-project/budgie-desktop) (based on GTK3) 
The issue occurs on both work and private notebooks and desktops.

See this screenshot to illustrate the behaviour: 
https://i.postimg.cc/434B7br3/Screenshot-from-2020-01-09-15-55-32.png

Making the screenshot I noticed the following:
The problem does not occur when opening a reply to message or new message in a new window.

I didn't test on other linux desktop environments, I can do this is this is helpful

**Comment by bvdlingen** [comment] 2020-01-09 15:28
I did some additional testing:

1. office 365 [theme settings](https://0x0.st/zRiT.png) don't make a difference 
2. office 365 [display density](https://0x0.st/zRiT.png) settings don't make a difference
3. behaviour occurs with both prebuild appimage and self build appimage

**Comment by eNkru** [comment] 2020-01-09 21:05
@bvdlingen thanks for the feedback.

Could you run the app by using `yarn start` or `npm start`, and check if the issue still occur? then check if the terminal throw any error or the build in developer tools (contrl + shift + i) throw any error in the console? another testing is using Chrome with the web version, see if that also have this issue.

I am working wit the GNOME 3 and KDE plasma every day. Seems fine by me.

**Comment by eNkru** [comment] 2020-01-09 21:06
I reckon you will have the same issue in `yarn start`, but the chrome web all good.

That's what's been feedback by another user long times ago.

**Comment by bvdlingen** [comment] 2020-01-10 16:14
Wow that's interesting!

I didn't try that before, but when using ` yarn start` the issue does not occur.
Hence no error in the terminal.

**Comment by eNkru** [comment] 2020-01-12 21:08
That's strange. I used to work on the Ubuntu + Gnome and it was all good. Now I am switching to Fedora + Gnome 3, still couldn't reproduce the issue.

If `yarn start` doesn't have the issue, then the problem might caused by the Election builder when build the AppImage (some magics). 

Another try is using the .deb package if you are on the Debian. Not familiar with Solus, see what package can supported by Solus in the [Election builder](https://github.com/electron-userland/electron-builder). Then you can tweak the package.json a little bit to build your executable.

Another try can be upgrade the Electrion builder to the latest (22.2.0), currently it's on 20.x.x

**Comment by KurtPattyn** [comment] 2020-01-27 11:18
The same problem happens on my Ubuntu 18.04 installation.

**Comment by arthmoeros** [comment] 2020-02-12 14:15
Hi!

Awesome tool, came here to report that this issue also happens on Manjaro 18.1.5 with Cinnamon.

**Comment by eNkru** [comment] 2020-02-12 22:26
really keen to fix this. as I couldn't reproduce this issue. appreciated if someone can always reproduce this issue find the root cause for me? to debug this issue, best run the app from the source code with `npm run start` or `yarn start`. The console will remain open to throw any error if occurred. also the developer tools of build in chromium can be enabled. see if any error in the console. 

I reckon this issue is caused by javascript or css issues in chromium on particular platform.

**Comment by arthmoeros** [comment] 2020-02-13 01:05
> really keen to fix this. as I couldn't reproduce this issue. appreciated if someone can always reproduce this issue find the root cause for me? to debug this issue, best run the app from the source code with `npm run start` or `yarn start`. The console will remain open to throw any error if occurred. also the developer tools of build in chromium can be enabled. see if any error in the console.
> 
> I reckon this issue is caused by javascript or css issues in chromium on particular platform.

Just tried on a vm with Manjaro 18.1.5 with Cinnamon I have at home, reproduced the issue running directly from the source but no error in console 😕

**Comment by eNkru** [comment] 2020-02-13 22:36
> > really keen to fix this. as I couldn't reproduce this issue. appreciated if someone can always reproduce this issue find the root cause for me? to debug this issue, best run the app from the source code with `npm run start` or `yarn start`. The console will remain open to throw any error if occurred. also the developer tools of build in chromium can be enabled. see if any error in the console.
> > I reckon this issue is caused by javascript or css issues in chromium on particular platform.
> 
> Just tried on a vm with Manjaro 18.1.5 with Cinnamon I have at home, reproduced the issue running directly from source but no error in console

according the feedback, the email can be still send to the correct contact. So I reckon it's just a UI rendering issue. The contact is not visible in the right place.

If you familiar with the HTML and CSS, probably can find out why it's not visible from the follow source code.

![image](https://user-images.githubusercontent.com/13460738/74484740-0afa2400-4f1e-11ea-9ae1-1c07577ccb84.png)

I didn't customize that part of logic though. One possibility is due to the app hide the ads on the right side. This might change the layout a little bit and may cause that contact div shift to somewhere else.

Really need to drill into the root cause, so can be a fix.

**Comment by eNkru** [comment] 2020-02-13 22:39
another thing to verify my guess is remove the vertical ads class value in setting and restart the app.

You will see the long vertical ads bar on the right side. Then check if you still having the issue :)

**Comment by arthmoeros** [comment] 2020-02-13 23:48
> another thing to verify my guess is remove the vertical ads class value in setting and restart the app.
> 
> You will see the long vertical ads bar on the right side. Then check if you still having the issue :)

Ah!, I see, you may be on to something, I just set another class name for all ads and the issue no longer reproduces, both on the latest AppImage and from source.

I'm at an enterprise office365 subscription so no ads. Maybe that's why you can't reproduce it?

**Comment by eNkru** [comment] 2020-02-14 00:09
> > another thing to verify my guess is remove the vertical ads class value in setting and restart the app.
> > You will see the long vertical ads bar on the right side. Then check if you still having the issue :)
> 
> Ah!, I see, you may be on to something, I just set another class name for all ads and the issue no longer reproduces, both on the latest AppImage and from source.
> 
> I'm at an enterprise office365 subscription so no ads. Maybe that's why you can't reproduce it?

Thanks for trying out. I reckon we make some progress onto this. I'll change the way handling the ads blocker in the next few days.

**Comment by dcioccarelli** [comment] 2020-05-18 12:23
Hi all,

any update on this? Just a confirmation that it also happens for me and I'm using a corporate Outlook subscription. So must have something to do with the logic to hide the ads. It is a little bit frustrating and can lead to e-mails being sent to unintended recipients.

Best regards,
Dominic.

**Comment by eNkru** [comment] 2020-05-18 23:32
> Hi all,
> 
> any update on this? Just a confirmation that it also happens for me and I'm using a corporate Outlook subscription. So must have something to do with the logic to hide the ads. It is a little bit frustrating and can lead to e-mails being sent to unintended recipients.
> 
> Best regards,
> Dominic.

Hi @dcioccarelli, thank you to support the app.

There is a workaround for this issue. If you are using corporate outlook subscription, there shouldn't be any vertical ADs unit on the right side. What you can do is adding a invalid class name into the setting. The VERTICAL ADS CLASS is the one you looking for. Just type some random number inthere will do :)

![image](https://user-images.githubusercontent.com/13460738/82268877-2c0e5d00-99c4-11ea-8c36-260cb9c4897e.png)

Please leave some feedback see if this will fix your problem :)

**Comment by AndresBott** [comment] 2020-05-22 11:36
I can confirm that the workaround works for corporate outlook subscription. maybe add a note to the readme?
also add a note that to access the settings window right click on the system tray icon, (took me a good hour to find) 
OS: ubuntu 18.04 LTS

**Comment by dcioccarelli** [comment] 2020-05-22 12:28
Hi @eNkru ! It worked. At first I just added random text in the vertical ads class and it didn't work. Only when I had added it to all three classes did it work.

Maybe add a checkbox to the UI for corporate users which automatically adds random text and disables the text entry boxes?

**Comment by eNkru** [comment] 2020-05-25 22:50
> I can confirm that the workaround works for corporate outlook subscription. maybe add a note to the readme?
> also add a note that to access the settings window right click on the system tray icon, (took me a good hour to find)
> OS: ubuntu 18.04 LTS

Thank you for the confirmation. I'll update the README

**Comment by eNkru** [comment] 2020-05-25 22:50
> Hi @eNkru ! It worked. At first I just added random text in the vertical ads class and it didn't work. Only when I had added it to all three classes did it work.
> 
> Maybe add a checkbox to the UI for corporate users which automatically adds random text and disables the text entry boxes?

I'll re-arrange the setting panel layout for easy use :)

**Comment by eNkru** [comment] 2020-08-06 02:26
Finally this issue should be fixed. I couldn't reproduce the error anymore. Feel free to re-open this ticket if you still having the issue.

**Closed by eNkru** 2020-08-06 02:26 UTC

**Comment by jctaillandier** [comment] 2020-08-26 20:11
Same fix for non-corporate outlook (hotmail.com) on Ubuntu 18.04. Cheers folks

**Comment by jctaillandier** [comment] 2020-08-26 20:14
Adding invalid class to first field only doesn't do it for non-corporate accounts (hotmail.com) on ubuntu 18.04, but I added in all 4 fields  and it seems to do the trick!

**Comment by eNkru** [comment] 2020-08-27 23:15
> Adding invalid class to first field only doesn't do it for non-corporate accounts (hotmail.com) on ubuntu 18.04, but I added in all 4 fields and it seems to do the trick!

could you try my last commit. It should fix the issue and you don't need to do this workaround anymore.

**Comment by jctaillandier** [comment] 2020-08-27 23:33
Confirmed last commit fixes with 0 such field change, cheers!
